[dependencies]
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
sha1 = "0.10"
rand = "0.8"
base64 = "0.21"
chrono = "0.4"
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1.6", features = ["v4"] }
urlencoding = "2.1"