/*
 Includes code from:
 CryptoJS
 code.google.com/p/crypto-js
 (c) 2009-2012 by Jeff Mott. All rights reserved.
 code.google.com/p/crypto-js/wiki/License
 Includes code from:
 PluginDetect v0.9.1
 www.pinlady.net/PluginDetect/license/
 [ QuickTime Flash Shockwave WindowsMediaPlayer Silverlight VLC AdobeReader RealPlayer ]
 [ isMinVersion getVersion hasMimeType onDetectionDone onWindowLoaded ]
 [ AllowActiveX ]
 Includes code from:
 http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript
 Includes code from:
 http://stackoverflow.com/questions/8253136/how-to-get-domain-name-only-using-javascript/8253221#8253221
 Includes code from:
 https://github.com/Valve/fingerprintjs2
 Copyright (c) 2018? Jonas Haag (jonas@lophus.org)
 Copyright (c) 2015? Valentin Vasilyev (valentin.vasilyev@outlook.com)
 Licensed under the MIT (http://www.opensource.org/licenses/mit-license.php) license.
*/
var _sift=_sift||[];function __siftFlashCB(u){_sift.push(["_setFlash",u])}window.__siftFlashCB=__siftFlashCB;
var Sift=Sift||function(){function u(b,g){for(var j=q(b),m=b.length;0<j.length&&j.length>g;)m=Math.floor(m/2),j=q(b.substring(0,m));return j}function E(b){var g="",j=0,m;for(m in b)if(b.hasOwnProperty(m)){var v=b[m];void 0===v||(null===v||"undefined"===v||"null"===v)||(0<j&&(g+="&"),g+=m+"="+v,j++)}return g}function K(){var b=window.location.hostname,g=b.split(".");if(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(b))return b;if(1==g.length)return null;for(var b="",j=0;2>j;){j++;var m=g[g.length-j],
b=m+(1<j?".":"")+b;if(-1!=";ac;ad;ae;aero;af;ag;ai;al;am;an;ao;aq;ar;arpa;as;asia;at;au;aw;ax;az;ba;bb;bd;be;bf;bg;bh;bi;biz;bj;bm;bn;bo;br;bs;bt;bv;bw;by;bz;ca;cat;cc;cd;cf;cg;ch;ci;ck;cl;cm;cn;co;com;coop;cr;cu;cv;cx;cy;cz;de;dj;dk;dm;do;dz;ec;edu;ee;eg;er;es;et;eu;fi;fj;fk;fm;fo;fr;ga;gb;gd;ge;gf;gg;gh;gi;gl;gm;gn;gov;gp;gq;gr;gs;gt;gu;gw;gy;hk;hm;hn;hr;ht;hu;id;ie;il;im;in;info;int;io;iq;ir;is;it;je;jm;jo;jobs;jp;ke;kg;kh;ki;km;kn;kp;kr;kw;ky;kz;la;lb;lc;li;lk;lr;ls;lt;lu;lv;ly;ma;mc;md;me;mg;mh;mil;mk;ml;mm;mn;mo;mobi;mp;mq;mr;ms;mt;mu;museum;mv;mw;mx;my;mz;na;name;nc;ne;net;nf;ng;ni;nl;no;np;nr;nu;nz;om;org;pa;pe;pf;pg;ph;pk;pl;pm;pn;pr;pro;ps;pt;pw;py;qa;re;ro;rs;ru;rw;sa;sb;sc;sd;se;sg;sh;si;sj;sk;sl;sm;sn;so;sr;st;su;sv;sy;sz;tc;td;tel;tf;tg;th;tj;tk;tl;tm;tn;to;tp;tr;travel;tt;tv;tw;tz;ua;ug;uk;us;uy;uz;va;vc;ve;vg;vi;vn;vu;wf;ws;ye;yt;za;zm;zw;".indexOf(";"+
m+";")){b=g[g.length-j-1]+"."+b;break}}return b}function L(b){var g=new Image(1,1);g.onload=function(){g.onload=null;g.onerror=null};g.onerror=function(){g.onload=null;g.onerror=null};var j=Math.ceil(1E6*Math.random()).toString();g.src="https://"+F+"/images/"+j+".gif?"+b}function s(b,g,j){var m=PluginDetect.getVersion(j);m?b[g]=m:-0.25<=PluginDetect.isMinVersion(j,0)&&(b[g]="unk")}function M(b,g){function j(){var v=(new Date).getTime(),h=!1;do if(m<b.length)window.SIFT_DEBUG&&window.performance&&
window.performance.mark(b[m].toString().substring(0,50)),b[m](),m+=1,window.SIFT_DEBUG&&window.performance&&b[m]&&(window.performance.mark(b[m].toString().substring(0,50)),window.performance.measure(b[m-1].toString().substring(0,50),b[m-1].toString().substring(0,50),b[m].toString().substring(0,50)));else{h=!0;break}while(100>(new Date).getTime()-v);h||setTimeout(j,g)}var m=0;setTimeout(j,g)}function N(){function b(){g.sessionId_||(z?g.sessionId_=t.MD5(z.toString()):g.userUuid_&&(g.sessionId_=t.MD5(g.userUuid_)))}
var g={random_:Math.ceil(1E9*Math.random()),version_:O,beaconKey_:G};A&&(g.userId_=q(A));b();B&&(g.partnerUserId_=q(B));var j={},m=!1;M([function(){var b;a:{b=document.cookie;var h=H+"=",i=b.indexOf("; "+h);if(i==-1){i=b.indexOf(h);if(i!==0){b=void 0;break a}}else i=i+2;var a=b.indexOf(";",i);if(a==-1)a=b.length;b=P(b.substring(i+h.length,a))}if(!b||b.length<15||b==="undefined"||b==="null"){h=b=void 0;b=n&&(n.crypto||n.msCrypto)||{};if(typeof b.getRandomValues==="function")for(var h="",i=["8","9",
"a","b"],a=new Uint8Array(1),c=0;c<36;c=c+1){var d="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".charAt(c);if(d==="x"){b.getRandomValues(a);h=h+(a[0]%16).toString(16)}else d==="y"&&(h=h+Math.floor(Math.random()*i.length))}else for(h=b="";b++<36;h=h+(b*51&52?(b^15?8^Math.random()*(b^20?16:4):4).toString(16):"-"));b=h;i=b;a=new Date;a.setFullYear(a.getFullYear()+Q);h=H;i=q(i);a=a.toGMTString();c=C===void 0?K():C;document.cookie=h+"="+i+(a?";expires="+a:"")+";path=/"+(c?";domain=."+c:"")}g.userUuid_=b},function(){var b;
b="";try{b=n.top.document.referrer}catch(h){if(n.parent)try{b=n.parent.document.referrer}catch(i){b=""}}if(b==="")b=x.referrer;if(b!=="")g.referrer_=u(b,200)},function(){if(x){g.title_=u(x.title,R);g.characterSet_=q(x.characterSet||x.charset)}},function(){if(n){g.url_=u(n.location.href,200);g.hostName_=u(n.location.hostname,200);try{g.sessionStorage_=!!n.sessionStorage}catch(b){g.sessionStorage_=true}try{g.localStorage_=!!n.localStorage}catch(h){g.localStorage_=true}try{g.indexedDB_=!!n.indexedDB}catch(i){g.indexedDB_=
true}g.openDB_=n.openDatabase==true}},function(){if(r){g.screenHeight_=r.height;g.screenWidth_=r.width;g.colorDepth_=r.colorDepth}},function(){if(l){g.platform_=q(l.platform);g.language_=q(l.language||l.browserLanguage);g.userAgent_=u(l.userAgent,200);g.cookieEnabled_=l.cookieEnabled;g.doNotTrack_=l.doNotTrack;g.maxTouchPoints_=l.maxTouchPoints;g.online_=l.onLine;g.product_=q(l.product);g.productSub_=q(l.productSub);g.vendor_=q(l.vendor);g.vendorSub_=q(l.vendorSub);g.hardwareConcurrency_=l.hardwareConcurrency;
g.javaEnabled_=l.javaEnabled();g.cpuClass_=q(l.cpuClass)}},function(){var b=new Date;g.timezoneOffset_=b.getTimezoneOffset();b.setDate(1);b.setMonth(6);var h=b.getTimezoneOffset();b.setMonth(12);b=b.getTimezoneOffset();g.dstOffset_=Math.abs(Math.abs(b)-Math.abs(h))},b,function(){for(var b=l.mimeTypes,h=b?b.length:0,i="",a=0;a<h;a++)i=i+b[a].type;g.numMimeTypes_=h;g.mimeTypesHash_=t.MD5(i)},function(){for(var b=l.plugins,h=b?b.length:0,i="",a=0;a<h;a++)var c=b[a],i=i+(c.name+c.description+c.filename+
c.length);g.numPlugins_=h;g.pluginsHash_=t.MD5(i)},function(){PluginDetect.getVersion(".")},...

...abridged...

...plugins:["VLC Web Plugin","VLC Multimedia Plug-in","VLC Multimedia Plugin","VLC multimedia plugin"],query:function(){var a,c;c=this.hasRun||!b.hasMimeType(this.mimeType);this.hasRun=1;if(c)return this;if(c=b.pd.findNavPlugin({find:this.find,avoid:this.avoid,mimes:this.mimeType,plugins:this.plugins}))if(this.installed=1,c.description&&(a=b.getNum(c.description+"","[\\d][\\d\\.]*[a-z]*")),a=b.getPluginFileVersion(c,a))this.version=a;return this}},
instance:{hasRun:0,installed:0,version:null,mimeType:"application/x-vlc-plugin",HTML:0,isDisabled:function(){var a=1;this.hasRun||(b.dbug?a=0:l.nav.installed&&b.hasMimeType(this.mimeType)&&(a=0));return a},query:function(){var a=b.DOM.altHTML,c=null,d=0,d=this.isDisabled();this.hasRun=1;if(d)return this;this.HTML=b.DOM.insert("object",["type",this.mimeType],"autoplay no loop no volume 0".split(" "),a,l);if(d=this.HTML.obj()){try{c||(c=b.getNum(d.VersionInfo))}catch(e){}try{c||(c=b.getNum(d.versionInfo()))}catch(f){}}c&&
(this.version=c,this.installed=1);return this}},axo:{hasRun:0,installed:0,version:null,progID:"VideoLAN.VLCPlugin",query:function(){var a;a=this.hasRun;this.hasRun=1;if(a)return this;if(a=b.getAXO(this.progID))if(this.installed=1,a=b.getNum(b.pd.getPROP(a,"VersionInfo"),"[\\d][\\d\\.]*[a-z]*"))this.version=a;return this}},codebase:{classID:"clsid:9BE31822-FDAD-461B-AD51-BE1D1C159921",isMin:function(a){this.$$=l;return b.codebase.isMin(this,a)},search:function(){this.$$=l;return b.codebase.search(this)},
DIGITMAX:[[11,11,16]],DIGITMIN:[0,0,0,0],Upper:["999"],Lower:["0"],convert:[1]}};b.addPlugin("vlc",l);var h={OTF:null,setPluginStatus:function(){var a=this.OTF,c=this.nav.precision,d=this.nav.version,e=0<this.nav.detected,f=this.axo.detected,g=this.axo.version,h=this.axo.precision,i=this.doc.detected,j=this.doc.version,l=this.doc.precision,m=this.doc2.detected,n=this.doc2.precision,d=this.doc2.version||d||g||j,c=n||c||h||l,e=0<m||e||0<f||0<i,d=d||null;this.version=b.formatNum(d);this.precision=c;
c=-1;if(3==a)c=this.version?0.5:-0.5;else if(d)c=1;else if(e)c=0;else if(-0.5==f||-0.5==i)c=-0.15;else if(b.browser.isIE&&(!b.browser.ActiveXEnabled||b.browser.ActiveXFilteringEnabled))c=-1.5;this.installed=c;1!=this.getVersionDone&&(a=1,this.verify&&this.verify.isEnabled()||0.5==this.installed||-0.5==this.installed?a=0:1==this.doc2.isDisabled()&&(a=0),this.getVersionDone=a)},getVersion:function(a,c){var d=0,e=this.verify;null===this.getVersionDone&&(this.OTF=0,e&&e.init());b.file.save(this,".pdf",
c);if(0!==this.getVersionDone){if((!d||b.dbug)&&this.nav.query().version)d=1;if((!d||b.dbug)&&this.axo.query().version)d=1;(!d||b.dbug)&&this.doc.query()}this.doc2.insertHTMLQuery();this.setPluginStatus()},getPrecision:function(a,c,d){if(b.isString(a)){var c=c||"",d=d||"",e,f=["\\d+","\\d+","\\d+","\\d+"];for(e=4;0<e;e--)if(RegExp(c+f.slice(0,e).join("[\\.]")+d).test(a))return e}return 0},nav:{detected:0,version:null,precision:0,mimeType:["application/pdf","application/vnd.adobe.pdfxml"],find:"Adobe.*PDF.*Plug-?in|Adobe.*Acrobat.*Plug-?in|Adobe.*Reader.*Plug-?in",
plugins:["Adobe Acrobat","Adobe Acrobat and Reader Plug-in","Adobe Reader Plugin"],query:function(){var a,c=null;if(this.detected||!b.hasMimeType(this.mimeType))return this;this.detected=(a=b.pd.findNavPlugin({find:this.find,mimes:this.mimeType,plugins:this.plugins}))?1:-1;a&&(c=b.getNum(a.description)||b.getNum(a.name),(c=b.getPluginFileVersion(a,c))||(c=this.attempt3()),c&&(this.version=c,this.precision=h.getPrecision(c)));return this},attempt3:function(){var a=null;1==b.OS&&(b.hasMimeType("application/vnd.adobe.pdfxml")?
a="9":b.hasMimeType("application/vnd.adobe.x-mars")?a="8":b.hasMimeType("application/vnd.adobe.xfdf")&&(a="6"));return a}},activexQuery:function(a){var c="",d,e,f={precision:0,version:null};try{a&&(c=a.GetVersions()+"")}catch(g){}if(c&&b.isString(c)&&(a=/\=\s*[\d\.]+/g,e=c.match(a))){for(a=0;a<e.length;a++)if((d=b.formatNum(b.getNum(e[a])))&&(!f.version||0<b.compareNums(d,f.version)))f.version=d;f.precision=h.getPrecision(c,"\\=\\s*")}return f},axo:{detected:0,version:null,precision:0,progID:["AcroPDF.PDF",
"AcroPDF.PDF.1","PDF.PdfCtrl","PDF.PdfCtrl.5","PDF.PdfCtrl.1"],progID_dummy:"AcroDUMMY.DUMMY",query:function(){var a=h,c,d,e,f,g;if(this.detected)return this;this.detected=-1;c=b.getAXO(this.progID_dummy);c||(g=b.errObj);for(f=0;f<this.progID.length;f++)if(c=b.getAXO(this.progID[f])){if(this.detected=1,c=a.activexQuery(c),d=c.version,e=c.precision,!b.dbug&&d)break}else g&&(b.errObj&&g!==b.errObj&&g.message!==b.errObj.message)&&(this.detected=-0.5);d&&(this.version=d);e&&(this.precision=e);return this}},
doc:{detected:0,version:null,precision:0,classID:"clsid:CA8A9780-280D-11CF-A24D-444553540000",classID_dummy:"clsid:CA8A9780-280D-11CF-A24D-BA9876543210",DummySpanTagHTML:0,HTML:0,DummyObjTagHTML1:0,DummyObjTagHTML2:0,isDisabled:function(){var a=0;this.HTML?a=1:b.dbug||b.DOM.isEnabled.objectTagUsingActiveX()||(a=1);return a},query:function(){var a=h,c=b.DOM.altHTML,d;if(this.isDisabled())return this;d=b.DOM.iframe.insert(99,"Adobe Reader");this.DummySpanTagHTML=b.DOM.insert("",[],[],c,a,1,d);this.HTML=
b.DOM.insert("object",["classid",this.classID],[],c,a,1,d);this.DummyObjTagHTML2=b.DOM.insert("object",["classid",this.classID_dummy],[],c,a,1,d);b.DOM.iframe.close(d);c=b.DOM.getTagStatus(this.HTML,this.DummySpanTagHTML,this.DummyObjTagHTML1,this.DummyObjTagHTML2,0,0,1);d=a.activexQuery(this.HTML.obj());a=d.version;d=d.precision;this.detected=0<c||a?1:-0.1==c||-0.5==c?-0.5:-1;a&&(this.version=a);d&&(this.precision=d);return this}},doc2:{detected:0,version:null,precision:0,classID:"clsid:CA8A9780-280D-11CF-A24D-444553540000",
mimeType:"application/pdf",HTML:0,count:0,count2:0,time2:0,intervalLength:25,maxCount:350,isDisabled:function(){var a=h,c=a.axo,d=a.nav,e=a.doc,f,g=0;if(this.HTML)g=2;else if(!b.dbug)if(b.DOM.isEnabled.objectTagUsingActiveX()){if(f=(d?d.version:0)||(c?c.version:0)||(e?e.version:0)||0,c=(d?d.precision:0)||(c?c.precision:0)||(e?e.precision:0)||0,!f||!c||2<c||0>b.compareNums(b.formatNum(f),b.formatNum("11")))g=2}else g=2;if(2>g&&(a=b.file.getValid(a),!a||!a.full))g=1;return g},handlerSet:0,onMessage:function(){var a=
this;return function(c){if(!a.version&&(a.detected=1,b.isArray(c)&&(c=c[0]),c=b.getNum(c+"")))/^(\d+)[.,_]?$/.test(c)?(c=RegExp.$1+",0,0,0",a.precision=3):/^(\d+)[.,_](\d)(\d\d)$/.test(c)||/^(\d+)[.,_](\d\d\d)(\d\d\d\d\d)$/.test(c)?(c=RegExp.$1+","+RegExp.$2+","+RegExp.$3+",0",a.precision=3):/^(\d+)[.,_](\d\d\d)(\d\d\d\d\d)(\d+)$/.test(c)?(c=RegExp.$1+","+RegExp.$2+","+RegExp.$3+","+RegExp.$4,a.precision=4):/^(\d+)[.,_](\d)(\d)$/.test(c)?(c=RegExp.$1+","+RegExp.$2+","+RegExp.$3+",0",a.precision=3):
/^(\d+)[.,_](\d)$/.test(c)&&(c=RegExp.$1+","+RegExp.$2+",0,0",a.precision=3),a.version=b.formatNum(c),h.setPluginStatus()}},isDefinedMsgHandler:function(a,b){try{return a?a.messageHandler!==b:0}catch(d){}return 1},queryObject:function(){var a=this.HTML;if(a=a?a.obj():0){if(!this.handlerSet&&this.isDefinedMsgHandler(a)){try{a.messageHandler={onMessage:this.onMessage()}}catch(b){}this.handlerSet=1;this.count2=this.count;this.time2=(new Date).getTime()}this.detected||(3<this.count&&!this.handlerSet?
this.detected=-1:this.time2&&(this.count-this.count2>=this.maxCount&&(new Date).getTime()-this.time2>=this.intervalLength*this.maxCount)&&(this.detected=-0.5))}},insertHTMLQuery:function(){var a=h,c=b.DOM.altHTML,d,e;if(this.isDisabled())return this;2>a.OTF&&(a.OTF=2);d=b.file.getValid(a).full;e=b.DOM.iframe.insert(0,"Adobe Reader");b.DOM.iframe.write(e,'<script type="text/javascript"><\/script>');this.HTML=b.DOM.insert("object",["data",d].concat(b.browser.isIE?["classid",this.classID]:["type",this.mimeType]),
["src",d],c,a,0,e);b.DOM.iframe.addHandler(e,this.onIntervalQuery);3>a.OTF&&this.HTML&&(a.OTF=3);b.DOM.iframe.close(e);return this},onIntervalQuery:function(){var a=h,c=a.doc2;c.count++;3==a.OTF&&(c.queryObject(),c.detected&&c.queryCompleted());3==a.OTF&&b.ev.setTimeout(c.onIntervalQuery,c.intervalLength)},queryCompleted:function(){var a=h;4!=a.OTF&&(a.OTF=4,a.setPluginStatus(),b.ev.callArray(a.DoneHndlrs))},z:0}};b.addPlugin("adobereader",h);var i={mimeType:["audio/x-pn-realaudio-plugin","audio/x-pn-realaudio"],
classID:"clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA",setPluginStatus:function(a,c){var d;c&&(this.version=b.formatNum(b.getNum(c)));this.installed=this.version?1:a?0:-1;this.getVersionDone=(d=(d=-1==this.installed||this.instance.version)||this.axo.version)?1:0},navObj:{hasRun:0,installed:null,version:null,find:"RealPlayer.*Plug-?in",avoid:"Totem|QuickTime|Helix|VLC|Download",plugins:["RealPlayer(tm) G2 LiveConnect-Enabled Plug-In (32-bit) ","RealPlayer(tm) G2 LiveConnect-Enabled Plug-In (64-bit) ",
"RealPlayer Plugin"],query:function(){var a=i,c=!this.hasRun&&b.hasMimeType(a.mimeType);this.hasRun=1;if(c&&(this.installed=(a=b.pd.findNavPlugin({find:this.find,avoid:this.avoid,mimes:a.mimeType,plugins:this.plugins}))?1:0,(a=b.getPluginFileVersion(a))&&0<=b.compareNums(b.formatNum(a),b.formatNum("15"))))this.version=a;return this}},JS:{hasRun:0,version:null,regStr:"RealPlayer.*Version.*Plug-?in",mimetype:"application/vnd.rn-realplayer-javascript",q1:[[11,0,0],[999],[663],[663],[663],[660],[468],
[468],[468],[468],[468],[468],[431],[431],[431],[372],[180],[180],[172],[172],[167],[114],[0]],q3:[[6,0],[12,99],[12,69],[12,69],[12,69],[12,69],[12,69],[12,69],[12,69],[12,69],[12,69],[12,69],[12,46],[12,46],[12,46],[11,3006],[11,2806],[11,2806],[11,2804],[11,2804],[11,2799],[11,2749],[11,2700]],compare:function(a,b){var d,e=a.length,f=b.length,g,h;for(d=0;d<Math.max(e,f);d++){g=d<e?a[d]:0;h=d<f?b[d]:0;if(g>h)return 1;if(g<h)return-1}return 0},convertNum:function(a,c,d){var e;if(!a||!(e=b.formatNum(a)))return null;
e=e.split(b.splitNumRegx);for(a=0;a<e.length;a++)e[a]=parseInt(e[a],10);if(0!==this.compare(e.slice(0,Math.min(c[0].length,e.length)),c[0]))return null;e=e.length>c[0].length?e.slice(c[0].length):[];if(0<this.compare(e,c[1])||0>this.compare(e,c[c.length-1]))return null;for(a=c.length-1;1<=a&&1!=a&&!(0===this.compare(c[a],e)&&0===this.compare(c[a],c[a-1]))&&!(0<=this.compare(e,c[a])&&0>this.compare(e,c[a-1]));a--);return d[0].join(".")+"."+d[a].join(".")},isEnabled:function(){return!this.hasRun&&1==
b.OS&&b.hasMimeType(this.mimetype)?1:0},query:function(){var a,c;c=this.isEnabled();this.hasRun=1;if(c&&((c=b.pd.findNavPlugin({find:this.regStr,mimes:this.mimetype}))&&(a=b.formatNum(b.getNum(c.description))),a)){var d=a.split(b.splitNumRegx);c=1;0>this.compare(d,[6,0,12,200])?c=-1:0>=this.compare(d,[6,0,12,1739])&&0<=this.compare(d,[6,0,12,857])&&(c=-1);0>c&&(this.version=(c=this.convertNum(a,this.q3,this.q1))?c:a)}return this}},instance:{hasRun:0,version:null,HTML:null,isEnabled:function(){var a=
i,c=1;if(b.DOM.isEnabled.objectTag()){if(!b.dbug&&(this.hasRun||b.DOM.isEnabled.objectTagUsingActiveX()||!b.hasMimeType(a.mimeType)||b.browser.isGecko&&0>b.compareNums(b.browser.verGecko,b.formatNum("1,8"))||b.browser.isOpera&&0>b.compareNums(b.browser.verOpera,b.formatNum("10"))))c=0}else c=0;return c},query:function(){var a=i,c=this.isEnabled();this.hasRun=1;if(c){this.HTML=b.DOM.insert("object",["type",a.mimeType[0]],"src  autostart false imagestatus false controls stopbutton".split(" "),"",a);
a=this.HTML.obj();try{this.version=b.getNum(a.GetVersionInfo())}catch(d){}b.DOM.setStyle(a,["display","none"])}return this}},axo:{hasRun:0,installed:null,version:null,progID:["rmocx.RealPlayer G2 Control","rmocx.RealPlayer G2 Control.1","RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)","RealVideo.RealVideo(tm) ActiveX Control (32-bit)","RealPlayer"],query:function(){var a,c,d;if(!this.hasRun){this.hasRun=1;for(c=0;c<this.progID.length;c++)if(a=b.getAXO(this.progID[c])){this.installed=1;d=0;try{d=
a.GetVersionInfo()+""}catch(e){}if(d&&(this.version=d,!b.dbug))break}}return this}},getVersion:function(a,c){var d=null,e=0;if((!e||b.dbug)&&this.axo.query().installed)e=1;if((!d||b.dbug)&&this.axo.query().version)d=this.axo.version;if((!e||b.dbug)&&this.navObj.query().installed)e=1;if((!d||b.dbug)&&this.navObj.query().version)d=this.navObj.version;if((!d||b.dbug)&&this.JS.query().version)e=1,d=this.JS.version;if((!e&&!d||c||b.dbug)&&this.instance.query().version)e=1,d=this.instance.version;this.setPluginStatus(e,
d)}};b.addPlugin("realplayer",i)})();for(var S=(new Date).getTime(),x=document,l=navigator,r=screen,n=window,q=n.encodeURIComponent,P=n.decodeURIComponent,F="hexagon-analytics.com",w,T=0,H="__ssid",z,B,A,G,C,Q=4,O=106,R=100,I=function(){for(var b=3,g=document.createElement("b"),j=g.all||[];g.innerHTML="<\!--[if gt IE "+ ++b+"]><i><![endif]--\>",j[0];);return 4<b?b:document.documentMode}(),y={_trackPageview:function(){N()},_setAccount:function(b){G=b},_setUserId:function(b){A=b},_setPartnerUserId:function(b){B=
b},_setSessionId:function(b){z=b},_setTrackerUrl:function(b){F=b},_setCookieDomain:function(b){C=b},_setFlash:function(b){w=b}},D=0;D<_sift.length;D++)J(_sift[D]);_sift={push:J}}();
//1676480626
